# Generated by Django 4.2.11 on 2024-03-17 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='description',
        ),
    ]
